### ISSUE TITLE
Do we still need to generate HTML?

### ISSUE THREAD

**Issue by kakra** [Zygo/nothing-to-see-here#1]
https://github.com/Zygo/nothing-to-see-here/blob/64281a00487c5e5217d3cde2d13fd4d80c7d134a/Makefile#L45

We could just point users to the Github pages instead... Would get rid of one external dependency, namely markdown.

**Comment by Zygo** [comment]
I like to preview the pages locally _before_ they show up in Github, although this repo is an obvious alternate solution.

I moved the HTML generation to the 'reallyall' target (or 'make doc') so it's not needed for non-developer builds any more.

I also set it up so it works the same way either through <https://zygo.github.io/bees/> or <https://github.com/Zygo/bees/>.  Or at least it will when I push there.

**Comment by Zygo** [comment]
These look good enough for now:

<https://github.com/Zygo/nothing-to-see-here/>
<https://zygo.github.io/nothing-to-see-here/>

Any last comments before I push to bees/master?

**Comment by kakra** [comment]
Yes: https://zygo.github.io/nothing-to-see-here/docs/gotchas.md = 404
Maybe other, I didn't check every link.

**Comment by Zygo** [comment]
Heh...the first link is bad.  :-P

I'm pretty sure I checked most of the others.

**Comment by kakra** [comment]
Meh... Works here: https://github.com/Zygo/nothing-to-see-here
But not on the site.

Vice versa with the other links.

**Comment by Zygo** [comment]
I get 404 at <https://zygo.github.io/bees/>,  but <https://zygo.github.io/bees/?> loads.  It looks like some kind of Github pages caching issue.  I'll give it a day to resolve itself.

**Comment by kakra** [comment]
Works here... Do you need to trigger jekyll rebuilding somehow? Maybe I've got the stale cache?

**Comment by kakra** [comment]
At least we see different versions, so it's probably not a server-side caching issue. You could (in Chrome at least) open the dev console with F12, then the reload button offers right-click options to force-reload the cache. I think Firefox offers some similar stuff.

**Comment by Zygo** [comment]
It loads fine now for me, without any special measures.

The github docs talk about soft limits for update rates on github pages, and my experience over the past days with pushes to n-t-s-h is that it is sometimes _really hard_ to get one of the pages to update.

**Comment by kakra** [comment]
I close this so it no longer shows up in my open issue list.
